DELIMITER $$
CREATE EVENT job03
ON SCHEDULE EVERY 1 HOUR
-- SE ELIGIO ESTA FRECUENCIA PARA QUE EL EVENTO PUEDA EJECTARSE CADA HORA Y ASI PODER VER QUE RESERVAS ESTAN VENCIDAS O DISPONIBLES EN UN LAPSO CORTO DE TIEMPO
DO
BEGIN
SELECT reserva_id, estado FROM reserva WHERE estado = 'aprobada' AND fecha_fin < NOW();
UPDATE reserva SET estado = 'expirada' WHERE estado = 'aprobada' AND fecha_fin < NOW();
END $$
DELIMITER ;
